---
title: "Vocabulary"
author: "David McAllister"
date: "31st October 2016"
output:
  pdf_document: default

---

see also http://cran.r-project.org/doc/contrib/Short-refcard.pdf

# Vocabulary which may be needed for questions

### Important operators and assignment
%in%, match
=, <-, <<-
$, [, [[, head, tail, subset
with
*assign, get*

### Comparison 
all.equal, identical
!=, ==, >, >=, <, <=
is.na, complete.cases
is.finite

### Basic math
*, +, -, /, ^, %%, %/%
abs, sign
ceiling, floor, round, trunc, signif
exp, log, log10, log2, sqrt
max, min, prod, sum
cummax, cummin, cumprod, cumsum, diff
pmax, pmin
range
mean, median, cor, sd, var


### Functions to do with functions
function
*missing*
*on.exit*
return, invisible

### Logical & sets 
&, |, !, xor
all, any
intersect, union, setdiff, setequal
which

### Vectors and matrices
c, matrix
automatic coercion rules  character > numeric > logical
vector
length, dim, ncol, nrow
cbind, rbind
names, colnames, rownames
t
*diag*
*sweep*
as.matrix, data.matrix

### Making vectors 
c
rep, rep_len
seq, seq_len, seq_along
rev
sample

### Lists & data.frames 
list, unlist
data.frame, as.data.frame
split
expand.grid

### Control flow 
if, &&, || (short circuiting)
for, while
next, break
switch
ifelse

### Apply & friends
lapply, sapply
apply
tapply

### Character manipulation 
grep, agrep
gsub
strsplit
chartr
nchar
tolower, toupper
substr
paste
library(stringr)

### Factors 
factor, levels
reorder, relevel
cut, findInterval
interaction
options(stringsAsFactors = FALSE)

### Ordering and tabulating 
duplicated, unique
merge
order, rank, quantile
sort
table, ftable

### Random variables 
(q, p, d, r) * (beta, binom, cauchy, chisq, exp, f, gamma, geom, 
  hyper, lnorm, logis, multinom, nbinom, norm, pois, signrank, t, 
  unif, weibull, wilcox, birthday, tukey)

###  Workspace 
ls, exists, rm
getwd, setwd
q
source
install.packages, library, require

### Help
help, ?
help.search, ??
example
vignette

### Reading and writing data
data
read.csv, write.csv
read.delim, write.delim
read.fwf
readLines, writeLines
load, save
library(foreign)

# Back to lecture